### ISSUE TITLE
Unsized array 

### ISSUE THREAD

**Issue by wrightwriter** [laurentlb/shader-minifier#464]
Repro:
```glsl
    int[] letters = int[](
        99, 114, 105, 109, 115, 111, 110, 90, 118, 111, 105, 100
    );
```

Results in 
```bash
System.AggregateException: One or more errors occurred. ---> System.Exception: Parse error: Error in src\shaders\abstract_post.frag: Ln: 160 Col: 11
    int[] letters = int[](
          ^
Expecting: infix operator, postfix operator, ',' or ';'

Traceback (most recent call last):
  File "minify_shaders.py", line 38, in <module>
    subprocess.run(full_command, shell=True, check=True)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
```

Fix:
```glsl
    int[12] letters = int[](
        99, 114, 105, 109, 115, 111, 110, 90, 118, 111, 105, 100
    );
```
Version 1.4.0

**Comment by plurry** [comment]
This is still a problem in 1.5.1. Probably related to #455.
