### ISSUE TITLE
Regression: Expecting: Type qualifier, ';' or 'layout'

### ISSUE THREAD

**Issue by Lutymane** [laurentlb/shader-minifier#474]
Getting an error in 1.4.0. while 1.3.6. runs correctly

Test code:

```glsl
highp float random(vec2 co)
{
    highp float a = 12.9898;
    highp float b = 78.233;
    highp float c = 43758.5453;
    highp float dt= dot(co.xy ,vec2(a,b));
    highp float sn= mod(dt,3.14);
    return fract(sin(sn) * c);
}

void main() {
    gl_FragColor.r = random(gl_FragCoord.xy);
}
```

Error:
```
2 tupledArg)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map@1401-2.Invoke(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map[T,TResult](FSharpFunc`2 mapping, T[] array)
   at ShaderMinifier.Minifier.minify(Options options, Tuple`2[] files)
   at ShaderMinifier.Minifier..ctor(Options options, Tuple`2[] files)
   at Main.minifyFiles(Options options, IEnumerable`1 filenames, TextWriter out)
   at Main.run(Options options, IEnumerable`1 filenames)
---> (Inner Exception #0) System.Exception: Parse error: Error in stdin: Ln: 1 Col: 7
highp float random(vec2 co)
      ^
Expecting: Type qualifier, ';' or 'layout'

   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message)
   at <StartupCode$shader_minifier_lib>.$Api.parseAndRewrite@23.Invoke(Tuple`2 tupledArg)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map@1401-2.Invoke(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0
```

**Comment by laurentlb** [comment]
Should be the same as #478.
It's fixed now
